// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture3D<float2> srcTectonicTexture;
RWTexture3D<float2> srcHeightTexture;
RWTexture3D<float2> destHeightTexture;
RWTexture3D<float2> outputHeightTexture;
RWTexture3D<float2> outputTectonicTexture;

SamplerState linearClampSampler;

float4 plateRotations[25];

float4 tectonicPoints[1024];

int textureSize;
float planetRadius;

float t;

float4 QuatInverse(float4 q)
{
    return float4(-q.x,-q.y, -q.z, q.w);
}

// FOUND AT 
float4 QuatMul(float4 q1, float4 q2)
{
    return float4(
        q2.xyz * q1.w + q1.xyz * q2.w + cross(q1.xyz, q2.xyz),
        q1.w * q2.w - dot(q1.xyz, q2.xyz)
    );
}

float3 QuatRotate(float4 q, float3 v)
{
    float4 q_c = q * float4(-1, -1, -1, 1);
    return QuatMul(q, QuatMul(float4(v, 0), q_c)).xyz;
}


[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float3 worldPos = (id / float(textureSize - 1.0) - 0.5f) * planetRadius;
    
    float halfRadius = planetRadius / 2;
    float maxD = length(float3(halfRadius, halfRadius, halfRadius));
    
    float pixelValue = length(worldPos) / (maxD + 1) - 0.5f;
    
    if (pixelValue > -0.1f && pixelValue < 0.01f)
    {
        int closestPlateIndex = -1;
        float closestDistance = 1000000;
        // TODO: refactor this so that it is spread across threads for faster execution
        for (int i = 0; i < 1024; i++)
        {
            if (distance(worldPos, tectonicPoints[i].xyz) < closestDistance)
            {
                closestPlateIndex = tectonicPoints[i].w;
                closestDistance = distance(worldPos, tectonicPoints[i].xyz);

            }
        }
        
        float3 outDir = normalize(worldPos);
        float4 invRotation = QuatInverse(plateRotations[closestPlateIndex]);
        float3 srcDir = QuatRotate(invRotation, outDir);
        float3 srcWorldPos = srcDir * length(worldPos);
        uint3 srcIndex = uint3((srcWorldPos / planetRadius + 0.5) * (textureSize - 1));
        outputTectonicTexture[id] = srcTectonicTexture[srcIndex];
        uint3 destIndex = uint3((worldPos / planetRadius + 0.5) * (textureSize - 1));

        outputHeightTexture[id] = srcHeightTexture[id];
        
    }
    //float3 outDir = normalize(worldPos);
    //float3 uvw = outDir * 0.5 + 0.5;
    //uint3 srcIndex = uint3(uvw * (textureSize - 1));
    //float2 srcPlate = srcTectonicTexture[srcIndex];
    //outputTectonicTexture[id] = srcTectonicTexture[id];

}
